export const editorTheme = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'header', foreground: '1e40af', fontStyle: 'bold' },
    { token: 'bold', foreground: '1e40af', fontStyle: 'bold' },
    { token: 'italic', foreground: '1e40af', fontStyle: 'italic' },
    { token: 'code', foreground: '047857', background: 'f1f5f9' },
    { token: 'link', foreground: '1e40af', textDecoration: 'underline' },
    { token: 'list', foreground: '334155', fontStyle: 'bold' },
    { token: 'quote', foreground: '475569', fontStyle: 'italic' },
    { token: 'comment', foreground: '64748b', fontStyle: 'italic' },
    { token: 'string', foreground: '047857' },
    { token: 'keyword', foreground: '1e40af', fontStyle: 'bold' },
    { token: 'number', foreground: '047857' },
    { token: 'operator', foreground: '1e293b' },
    { token: 'delimiter', foreground: '1e293b' },
    { token: 'variable', foreground: '1e293b' },
    { token: 'function', foreground: '1e40af' },
    { token: 'type', foreground: '1e40af' },
    { token: 'tag', foreground: '1e40af' },
    { token: 'attribute', foreground: '047857' },
    { token: 'meta', foreground: '64748b' },
    { token: 'invalid', foreground: 'dc2626' }
  ],
  colors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#1e293b',
    'editor.lineHighlightBackground': '#f8fafc',
    'editor.lineHighlightBorder': '#e2e8f0',
    'editor.selectionBackground': '#e2e8f0',
    'editor.inactiveSelectionBackground': '#f1f5f9',
    'editorCursor.foreground': '#1e40af',
    'editorWhitespace.foreground': '#cbd5e1',
    'editorLineNumber.foreground': '#94a3b8',
    'editorLineNumber.activeForeground': '#1e40af',
    'editorGutter.background': '#ffffff',
    'editorGutter.modifiedBackground': '#fef3c7',
    'editorGutter.addedBackground': '#dcfce7',
    'editorGutter.deletedBackground': '#fee2e2',
    'editorBracketMatch.background': '#f1f5f9',
    'editorBracketMatch.border': '#cbd5e1',
    'editor.foldBackground': '#f8fafc',
    'editor.foldingControlForeground': '#94a3b8',
    'editor.foldingControlBackground': '#ffffff',
    'editor.foldingHighlightBackground': '#f8fafc',
    'editor.foldingHighlightBorder': '#e2e8f0',
    'editorGutter.foldingControlForeground': '#94a3b8',
    'editorGutter.foldingControlBackground': '#ffffff',
    'editorGutter.foldingControlHoverBackground': '#f8fafc',
    'editorGutter.foldingControlCollapsedForeground': '#1e40af',
    'editorGutter.foldingControlExpandedForeground': '#1e40af',
    'scrollbar.shadow': '#ffffff',
    'scrollbarSlider.background': '#cbd5e1',
    'scrollbarSlider.hoverBackground': '#94a3b8',
    'scrollbarSlider.activeBackground': '#64748b',
    'editorOverviewRuler.border': '#ffffff',
    'editorOverviewRuler.background': '#ffffff',
    'editorOverviewRuler.currentContentForeground': '#cbd5e1',
    'editorOverviewRuler.incomingContentForeground': '#cbd5e1',
    'editorOverviewRuler.commonContentForeground': '#cbd5e1'
  }
}; 